services:
  db:
    image: postgres
    container_name: postgres_db
    restart: always
    ports: 
      - "5432:5432"
    volumes:
      - db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"
    volumes:
      - redis-volume:/data
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/prometheus/prometheus.yml:ro
    ports:
      - 19090:9090
    command:
      - "--web.enable-lifecycle"
    restart: always
#    networks:
#      - promnet
    user: root

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./grafana-volume:/var/lib/grafana
    restart: always
#    networks:
#      - promnet
    ports:
      - 13030:3000
    user: root
#networks:
#  promnet:
#    driver: bridge
volumes:
  db-volume:
  redis-volume: