services:
  db:
    image: postgres
    container_name: postgres_db
    restart: always
    ports: 
      - "5432:5432"
    volumes:
      - db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"
    volumes:
      - redis-volume:/data
volumes:
  db-volume:
  redis-volume:
